import type { z } from "zod";
import type { packManifestSchema } from "@vcc-workflow/schema";
import { rolePacks } from "./role-packs";

type PackInput = z.input<typeof packManifestSchema>;

export const builtinPacks: PackInput[] = [
  {
    name: "screen-from-figma",
    version: "0.1.0",
    title: "Screen from Figma",
    description:
      "Paste a Figma frame link. Reads the design and builds a matching screen in this workspace's own stack.",
    roles: ["designer", "developer"],
    tags: ["figma", "frontend", "design-to-code"],
    triggers: ["build this figma", "figma to code", "implement the design"],
    agents: ["ui-ux-designer", "frontend-engineer", "reviewer"],
    skills: ["design-tokens", "accessibility", "code-review"],
    stages: [
      {
        id: "read-design",
        title: "Read design",
        agent: "ui-ux-designer",
        model: "opus",
        skills: ["design-tokens", "accessibility"],
        tools: ["figma"],
        instruction:
          "The Figma frame URL is in inputs.figmaUrl. Use the Figma MCP tools (e.g. mcp__figma__get_figma_data and mcp__figma__download_figma_images) to read that node. Produce a precise, implementation-ready UI spec: the component/layout tree, spacing and sizing, colors and typography mapped to design tokens, interactive states, and a list of any exported assets with where they were saved. Do not write component code in this step.",
      },
      {
        id: "implement",
        title: "Implement",
        agent: "frontend-engineer",
        model: "sonnet",
        skills: ["design-tokens"],
        tools: [],
        instruction:
          "First detect THIS workspace's frontend stack and conventions from its .claude rules (e.g. .claude/rules/frontend.md), CLAUDE.md, and existing components — framework, styling system, component-wrapper conventions, and file layout. Then implement the screen from the design spec as new component file(s) that match those conventions exactly (reuse existing wrapped components; do not introduce a different UI library). Write the files into the repository. Keep it token-efficient and accessible.",
        verify: "build",
      },
      {
        id: "review",
        title: "Review",
        agent: "reviewer",
        model: "sonnet",
        skills: ["code-review"],
        tools: [],
        instruction:
          "Review the generated component(s) against the workspace rules and the design spec: convention compliance, correctness, accessibility, and fidelity to the Figma frame. List any high-confidence issues with concrete fixes.",
      },
    ],
    levers: ["codegraph", "ponytail", "routing", "caveman"],
    guardrails: {
      maxRetries: 2,
      maxLoopDepth: 6,
      budget: { tokens: 2000000 },
      stageTimeoutMs: 600000,
      qualityThreshold: "advisory",
      onBreach: "pause",
      requireHumanGate: [],
      allowedTools: [],
      backgroundSpend: false,
    },
    trust: "verified",
  },
  {
    name: "eng-loop",
    version: "0.1.0",
    title: "Engineering Loop",
    description: "Requirement to output engineering loop, token-efficient.",
    roles: ["developer"],
    tags: ["engineering", "token-efficient"],
    triggers: ["build feature", "implement"],
    agents: ["analyst", "architect", "developer", "tester", "reviewer"],
    skills: ["spec-authoring", "codegraph-query", "ponytail"],
    stages: [
      {
        id: "requirement",
        title: "Requirement",
        agent: "analyst",
        model: "opus",
        skills: ["spec-authoring"],
        tools: [],
        gate: "human-approve",
      },
      {
        id: "analysis",
        title: "Analysis",
        agent: "architect",
        model: "opus",
        skills: ["codegraph-query"],
        tools: [],
      },
      {
        id: "coding",
        title: "Coding",
        agent: "developer",
        model: "sonnet",
        skills: ["ponytail", "codegraph-query"],
        tools: [],
        verify: "build",
      },
      {
        id: "testing",
        title: "Testing",
        agent: "tester",
        model: "haiku",
        skills: [],
        tools: [],
        verify: "tests",
      },
      {
        id: "output",
        title: "Output",
        agent: "reviewer",
        model: "sonnet",
        skills: [],
        tools: [],
      },
    ],
    levers: ["codegraph", "rtk", "ponytail", "routing"],
    guardrails: {
      maxRetries: 3,
      maxLoopDepth: 8,
      budget: { tokens: 2000000 },
      stageTimeoutMs: 600000,
      qualityThreshold: "verifier-must-pass",
      onBreach: "pause",
      requireHumanGate: ["output"],
      allowedTools: [],
      backgroundSpend: false,
    },
    trust: "verified",
  },
  {
    name: "tech-diagram",
    version: "0.1.0",
    title: "Architecture Diagram",
    description: "Repo to C4 / Mermaid architecture diagram.",
    roles: ["developer", "designer"],
    tags: ["architecture", "diagram"],
    triggers: ["draw architecture", "update diagram"],
    agents: ["analyst", "renderer"],
    skills: ["repo-scan", "mermaid-authoring"],
    stages: [
      {
        id: "scan",
        title: "Scan",
        agent: "analyst",
        model: "opus",
        skills: ["repo-scan", "codegraph-query"],
        tools: [],
      },
      {
        id: "render",
        title: "Render",
        agent: "renderer",
        model: "haiku",
        skills: ["mermaid-authoring"],
        tools: [],
        verify: "renders",
      },
    ],
    levers: ["codegraph", "caveman", "routing"],
    guardrails: {
      maxRetries: 2,
      maxLoopDepth: 4,
      budget: { tokens: 500000 },
      stageTimeoutMs: 300000,
      qualityThreshold: "verifier-must-pass",
      onBreach: "pause",
      requireHumanGate: [],
      allowedTools: [],
      backgroundSpend: false,
    },
    trust: "verified",
  },
  {
    name: "content-ops",
    version: "0.1.0",
    title: "Content Operations",
    description: "Requirement to a drafted, reviewed and delivered document.",
    roles: ["ba-po", "ops"],
    tags: ["content", "documents"],
    triggers: ["write a report", "draft content", "generate a doc"],
    agents: ["extractor", "writer", "reviewer", "notifier"],
    skills: ["requirement-analysis", "doc-authoring"],
    stages: [
      { id: "start", title: "Start", action: "start", agent: "system", model: "haiku", skills: [], tools: [] },
      {
        id: "gather",
        title: "Gather source",
        action: "extract-data",
        agent: "extractor",
        model: "haiku",
        skills: ["data-mapping"],
        tools: [],
      },
      {
        id: "draft",
        title: "Draft document",
        action: "generate-doc",
        agent: "writer",
        model: "sonnet",
        skills: ["doc-authoring"],
        tools: [],
      },
      {
        id: "review",
        title: "Review",
        action: "review",
        agent: "reviewer",
        model: "sonnet",
        skills: [],
        tools: [],
        verify: "quality",
      },
      {
        id: "approve",
        title: "Approve",
        action: "approval",
        agent: "approver",
        model: "sonnet",
        skills: [],
        tools: [],
        gate: "human-approve",
      },
      { id: "deliver", title: "Deliver", action: "notify", agent: "notifier", model: "haiku", skills: [], tools: [] },
      { id: "end", title: "End", action: "end", agent: "system", model: "haiku", skills: [], tools: [] },
    ],
    levers: ["routing", "caveman", "disclosure"],
    guardrails: {
      maxRetries: 2,
      maxLoopDepth: 4,
      budget: { tokens: 800000 },
      stageTimeoutMs: 300000,
      qualityThreshold: "advisory",
      onBreach: "pause",
      requireHumanGate: ["approve"],
      allowedTools: [],
      backgroundSpend: false,
    },
    trust: "verified",
  },
  {
    name: "data-sync",
    version: "0.1.0",
    title: "Data Sync",
    description: "Extract, reshape and summarize data, then export or notify.",
    roles: ["developer", "ops"],
    tags: ["data", "etl"],
    triggers: ["sync data", "process a spreadsheet", "etl"],
    agents: ["extractor", "transformer", "summarizer", "notifier"],
    skills: ["data-mapping"],
    stages: [
      { id: "start", title: "Start", action: "start", agent: "system", model: "haiku", skills: [], tools: [] },
      {
        id: "extract",
        title: "Extract",
        action: "extract-data",
        agent: "extractor",
        model: "haiku",
        skills: ["data-mapping"],
        tools: [],
      },
      {
        id: "transform",
        title: "Transform",
        action: "transform",
        agent: "transformer",
        model: "sonnet",
        skills: ["data-mapping"],
        tools: [],
      },
      {
        id: "summarize",
        title: "Summarize",
        action: "summarize",
        agent: "summarizer",
        model: "haiku",
        skills: [],
        tools: [],
      },
      { id: "export", title: "Export", action: "notify", agent: "notifier", model: "haiku", skills: [], tools: [] },
      { id: "end", title: "End", action: "end", agent: "system", model: "haiku", skills: [], tools: [] },
    ],
    levers: ["routing", "disclosure", "caveman"],
    guardrails: {
      maxRetries: 2,
      maxLoopDepth: 4,
      budget: { tokens: 600000 },
      stageTimeoutMs: 300000,
      qualityThreshold: "advisory",
      onBreach: "pause",
      requireHumanGate: [],
      allowedTools: [],
      backgroundSpend: false,
    },
    trust: "verified",
  },
  ...rolePacks,
];
